apiVersion: v1
kind: Service
metadata:
  name:  devopsidn-rtp-service
  namespace: devopsidn
spec:
  type: NodePort
  selector:
    app: devopsidn-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
